### ISSUE TITLE
Green not working on last panel

### ISSUE THREAD

**Issue by Untss** [hzeller/rpi-rgb-led-matrix#1467] opened 2022-09-26 18:39 UTC
Hello,

I have 6 HUB75 panels lined up in 2 rows 3 columns, I have them wired up like this:
![image](https://user-images.githubusercontent.com/76573735/192354562-be48c537-b666-4ff7-af3a-10dc0a3693c7.png)

the purple color shows my wiring, the red part is the part that isnt displaying green. 

im using a 5V 30A power supply and a raspberry pi a+, and I tested the colors using python

**Comment by anandrajgupta** [comment] 2022-09-27 03:00
try interchanging the Panel, if the issue is also interchanged then the Panel is Faulty.

**Comment by Untss** [comment] 2022-09-27 07:18
> try interchanging the Panel, if the issue is also interchanged then the Panel is Faulty.

I have already tried it with a brand new panel, and still green wont work in that corner.

**Comment by anandrajgupta** [comment] 2022-09-27 14:45
do not "change" it with a brand new panel, "interchange" it with the existing panel in the HUB row
if that also don't work, then 
try interchanging the FRC, try interchanging the power connector, try interchanging the Active-HAT being used, try to add another panel in the series and observe the result, try interchanging all possible hardware because problem is with hardware it is not software problem!

**Comment by Untss** [comment] 2022-09-27 15:17
I now swapped the last panel(bottom right) with the panel in the middle on the top, and this is the result.

No idea how to fix it
https://user-images.githubusercontent.com/76573735/192566376-1bf01f52-f76a-4b32-8a2c-5ee1281acec3.MOV

**Comment by anandrajgupta** [comment] 2022-09-27 15:21
Good

Either FRC or Panel is Faulty!

**Comment by Untss** [comment] 2022-09-27 15:23
Ayee it works

One of the panels is indeed faulty, swapped it with the brand new one

**Comment by anandrajgupta** [comment] 2022-09-27 15:43
All the best 👍🏻

**Comment by combs** [comment] 2023-05-07 23:52
Probably makes sense to close this issue out then?

**Closed** 2023-05-07 23:53 UTC
