### ISSUE TITLE
AZERONE 128x64 ABC FM6124 Led Matrix not working

### ISSUE THREAD

**Issue by jacksonhmg** [hzeller/rpi-rgb-led-matrix#1729] opened 2024-11-06 23:43 UTC
Hey guys,

I bought this panel:
https://www.amazon.com/gp/product/B0869P1DCH

It is: 
- 128x64
- ABC addressing (even though the description says ABCDE)
- Uses chips FM6124 and 74HC245C
- P2

![IMG_7035](https://github.com/user-attachments/assets/fea2e88e-14cc-4d2f-ba5f-b272738b5602)
![IMG_7036](https://github.com/user-attachments/assets/f6f46103-9562-4ce9-8b2d-fcb044abca5d)

And I cannot get it working with any configuration.

I noticed this similar issue:
https://github.com/hzeller/rpi-rgb-led-matrix/issues/823

and this:
https://github.com/hzeller/rpi-rgb-led-matrix/issues/1025

However neither of suggestions in them seem to work and the supplier can't provide me a schematic or datasheet for the device. 

For D0:

All --led-row-addr-type=0 variations all produce some variation of this result:
![row0](https://github.com/user-attachments/assets/a55df3b4-a72f-4e53-a951-dd3c17d09824)

All --led-row-addr-type=1 variations all produce some variation of this result:
![demo1](https://github.com/user-attachments/assets/c64b1d21-ea86-4f85-a259-c82ab5080ab0)

All --led-row-addr-type=3 variations all produce some variation of this result:
![row3](https://github.com/user-attachments/assets/24c5f7fb-5cec-4eb4-8b8a-c202d4ef6485)

Experimenting with multiplexing and chip settings has not given any good results.

Do these results signal anything to those more experienced?

(@marcmerlin i noticed you used a similar board, is there anything that stands out about my output? maybe a signal of poor powering?)

Any help would be really appreciated, thank you.

**Comment by marcmerlin** [comment] 2024-11-07 16:26
Ok, I had a look at my ABC and ABCDE panels from Azerone, and indeed you have the ABC.
First thing is I would contact azerone and ask for a replacement. The amazon listing says ABCDE and you got the wrong panel so they should send you the ones you paid for.
I'm sure you saw https://github.com/hzeller/rpi-rgb-led-matrix/issues/823 I posted in 2019, and strangely you got the same error than I did then, I contacted azerone and they sent me the correct panel. 
It's probably best if you go through amazon support, but if needed, you can contact https://www.facebook.com/su.hongren.9 from Azerone directly.

Now, as per the link I posted, those ABC panels, can work, mine did, but I chose not to work them since I was setup to use ABCDE and wanted all my panels to be compatible.

As per the other bug I linked, for me the ABCs did work with
~/rpi-rgb-led-matrix/examples-api-use/demo --led-rows=64 --led-cols=128 --led-chain=1 --led-show-refresh --led-pwm-dither-bits=1 --led-pwm-bits=7 --led-panel-type=FM6126A --led-row-addr-type=3 -D0 
but I still recommend you return them.

**Comment by marcmerlin** [comment] 2024-11-07 16:34
@hzeller  as per our discussion last weekend, I don't know how much I can promise to help with bug-wise, but can you either dupe this bug against #823 , or give me github bug admin access and I'll be happy to do so?

**Comment by marcmerlin** [comment] 2024-11-15 20:06
this is a dupe of the bug I linked, closing this

**Closed by marcmerlin** 2024-11-15 20:06 UTC
